export enum IngredientCategory {
  PROTEIN = 'PROTEIN',
  DAIRY = 'DAIRY',
  GRAIN = 'GRAIN',
  VEGETABLE = 'VEGETABLE',
  FRUIT = 'FRUIT',
  SPICE = 'SPICE',
  CONDIMENT = 'CONDIMENT',
  BEVERAGE = 'BEVERAGE',
  SNACK = 'SNACK',
  OTHER = 'OTHER',
}
